# Generated by Django 3.2.25 on 2026-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'ซื้อสินค้า (นำเข้า)'), ('SELL', 'ขายสินค้า (ส่งออก)'), ('INCOME', 'รายรับอื่นๆ'), ('EXPENSE', 'รายจ่ายอื่นๆ')], max_length=10, verbose_name='ประเภทรายการ')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อรายการ/สินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงิน (ไม่รวม VAT)')),
                ('has_vat', models.BooleanField(default=False, verbose_name='คิด VAT 7%')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอด VAT')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดสุทธิ (รวม VAT)')),
                ('date', models.DateField(verbose_name='วันที่ทำรายการ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
