# Generated by Django 3.2.25 on 2026-04-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='ไฟล์สลิป/ใบเสร็จ'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แท็ก/หมวดหมู่ย่อย'),
        ),
    ]
