# Generated by Django 3.2.25 on 2026-04-14 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_auto_20260414_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อลูกค้า / ซัพพลายเออร์')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('contact_type', models.CharField(choices=[('CUSTOMER', 'ลูกค้า'), ('SUPPLIER', 'ซัพพลายเออร์')], default='CUSTOMER', max_length=10, verbose_name='ประเภท')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสสินค้า')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='จำนวนในคลัง')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคากลางต่อหน่วย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'จ่ายแล้ว / ได้รับเงินแล้ว'), ('PENDING', 'ค้างชำระ / รอวางบิล'), ('CANCELLED', 'ยกเลิกรายการ')], default='PAID', max_length=20, verbose_name='สถานะการชำระเงิน'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='จำนวนหน่วย'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.contact', verbose_name='คู่ค้า'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.product', verbose_name='สินค้าในคลัง'),
        ),
    ]
