# Generated by Django 3.2.25 on 2026-04-14 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_auto_20260414_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('THB', 'THB (Thai Baht)'), ('USD', 'USD (US Dollar)'), ('CNY', 'CNY (Chinese Yuan)'), ('JPY', 'JPY (Japanese Yen)'), ('EUR', 'EUR (Euro)')], default='THB', max_length=3, verbose_name='สกุลเงิน'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='อัตราแลกเปลี่ยน'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expense_category',
            field=models.CharField(choices=[('N/A', 'ไม่ใช่รายจ่าย (N/A)'), ('COGS', 'ต้นทุนขาย (Cost of Goods Sold)'), ('OPEX', 'ค่าใช้จ่ายดำเนินงาน (Operational Expense)'), ('CAPEX', 'รายจ่ายลงทุน (Capital Expenditure)')], default='N/A', max_length=10, verbose_name='ประเภทค่าใช้จ่าย'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='foreign_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดเงินต่างประเทศ'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'ซื้อสินค้า (นำเข้า)'), ('SELL', 'ขายสินค้า (ส่งออก)'), ('INCOME', 'รายรับอื่นๆ'), ('EXPENSE', 'รายจ่ายอื่นๆ')], max_length=10, verbose_name='ประเภทรายการ')),
                ('status', models.CharField(choices=[('DRAFT', 'ฉบับร่าง (รอพิจารณา)'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ไม่อนุมัติ')], default='DRAFT', max_length=20, verbose_name='สถานะเอกสาร')),
                ('is_converted', models.BooleanField(default=False, verbose_name='แปลงเป็นบิลแล้ว')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวนหน่วย')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อรายการ/สินค้า')),
                ('currency', models.CharField(choices=[('THB', 'THB (Thai Baht)'), ('USD', 'USD (US Dollar)'), ('CNY', 'CNY (Chinese Yuan)'), ('JPY', 'JPY (Japanese Yen)'), ('EUR', 'EUR (Euro)')], default='THB', max_length=3, verbose_name='สกุลเงิน')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='อัตราแลกเปลี่ยน')),
                ('foreign_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดเงินต่างประเทศ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงิน (ไม่รวม VAT)')),
                ('has_vat', models.BooleanField(default=False, verbose_name='คิด VAT 7%')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอด VAT')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดสุทธิ (รวม VAT)')),
                ('expense_category', models.CharField(choices=[('N/A', 'ไม่ใช่รายจ่าย (N/A)'), ('COGS', 'ต้นทุนขาย (Cost of Goods Sold)'), ('OPEX', 'ค่าใช้จ่ายดำเนินงาน (Operational Expense)'), ('CAPEX', 'รายจ่ายลงทุน (Capital Expenditure)')], default='N/A', max_length=10)),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='แท็ก/หมวดหมู่ย่อย')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='ไฟล์สลิป/อ้างอิง')),
                ('date', models.DateField(verbose_name='วันที่ทำเอกสาร')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.contact', verbose_name='คู่ค้า')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.product', verbose_name='สินค้าในคลัง')),
            ],
        ),
    ]
